University.Web/Controllers/InstructorsController.cs
using PagedList;
using System;
using System.Linq;
using System.Web.Mvc;
using University.BL.Data;
using University.BL.DTOs;
using University.BL.Models;

namespace University.Web.Controllers
{
    public class InstructorsController : Controller
    {
        private readonly UniversityContext context = new UniversityContext();


        [HttpGet]
        public ActionResult Index(int? instructorID, int? pageSize, int? page)
        {
            #region Consluta Instructor
            var query = context.Instructors.ToList();

            var instructors = query.Where(x => x.HireDate < DateTime.Now)
                                .Select(x => new InstructorDTO
                                {
                                    ID = x.ID,
                                    FirstMidName = x.FirstMidName,
                                    LastName = x.LastName,
                                    HireDate = x.HireDate
                                }).ToList();


            #endregion


            #region Lista Instructores

            if (instructorID != null)
            {
                var deparments = (from q in context.Departments
                                  join r in context.Instructors on q.InstructorID equals r.ID
                                  where q.InstructorID == instructorID
                                  select new DepartmentDTO
                                  {

                                      DepartmentID = q.DepartmentID,
                                      Name = q.Name,
                                      Budget = q.Budget
                                  }).ToList();

                ViewBag.Deparments = deparments;
            }

            #endregion

            #region Paginacion
            //Si viene nulo dele 10 por defecto
            pageSize = (pageSize ?? 10);
            //si viene igual por defecto llevelo a la 1 
            page = (page ?? 1);
            ViewBag.pageSize = pageSize;
            #endregion 
            return View(instructors.ToPagedList(page.Value, pageSize.Value));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(InstructorDTO instructor)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(instructor);

                if (instructor.HireDate > DateTime.Now)
                    throw new Exception("La fecha no puede ser mayor a la fecha actual");

                //INSERT INTO Students(FirstMidName,LastName,EnrollmentDate) VALUES(@FirstMidName, @LastName, @EnrollmentDate)
                context.Instructors.Add(new Instructor
                {
                    FirstMidName = instructor.FirstMidName,
                    LastName = instructor.LastName,
                    HireDate = instructor.HireDate
                });
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View(instructor);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {

            var instructor = context.Instructors.Where(x => x.ID == id)
                                          .Select(x => new InstructorDTO
                                          {
                                              ID = x.ID,
                                              LastName = x.LastName,
                                              FirstMidName = x.FirstMidName,
                                              HireDate = x.HireDate
                                          }).FirstOrDefault();

            return View(instructor);
        }

        [HttpPost]
        public ActionResult Edit(InstructorDTO instructor)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(instructor);

                if (instructor.HireDate > DateTime.Now)
                    throw new Exception("La fecha no puede ser mayor a la fecha actual");
                var instructortModel = context.Instructors.FirstOrDefault(x => x.ID == instructor.ID);

                //campos que se van a modificar
                //sobreescribo las propiedades del modelo de base de datos
                instructortModel.LastName = instructor.LastName;
                instructortModel.FirstMidName = instructor.FirstMidName;
                instructortModel.HireDate = instructor.HireDate;
                //aplique los cambios en base de datos
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View(instructor);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (!context.Departments.Any(x => x.InstructorID == id) &&
                (!context.CourseInstructors.Any(x => x.InstructorID ==id)) && 
                (!context.OfficeAssignments.Any(x => x.InstructorID ==id)))
            {
                var instructortModel = context.Instructors.FirstOrDefault(x => x.ID == id);
                context.Instructors.Remove(instructortModel);
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    } //FIN CLASS CONTROLLER
} // FIN NAMESPACE

University.Web/Views/Instructors/Create.cshtml
@model University.BL.DTOs.InstructorDTO
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

<form action="/Instructors/Create" method="post">
   
    @Html.DisplayNameFor(m => m.LastName)
    @Html.EditorFor(m => m.LastName, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })


    @Html.DisplayNameFor(m => m.FirstMidName)
    @Html.EditorFor(m => m.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(m => m.FirstMidName, "", new { @class = "text-danger" })


    @Html.DisplayNameFor(m => m.HireDate)
    @Html.EditorFor(m => m.HireDate, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(m => m.HireDate, "", new { @class = "text-danger" })
    
    <hr />
    <input type="submit" value="Create" class="btn btn-primary" />



</form>

University.Web/Views/Instructors/Edit.cshtml
@model University.BL.DTOs.InstructorDTO
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@Html.ValidationSummary(false, "", new { @class = "text-danger" })

<form action="/Instructors/Edit" method="post">
    @Html.HiddenFor(m => m.ID)

    @Html.DisplayNameFor(m => m.LastName)
    @Html.EditorFor(m => m.LastName, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })

    @Html.DisplayNameFor(m => m.FirstMidName)
    @Html.EditorFor(m => m.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(m => m.FirstMidName, "", new { @class = "text-danger" })

    @Html.DisplayNameFor(m => m.HireDate)
    @Html.EditorFor(m => m.HireDate, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(m => m.HireDate, "", new { @class = "text-danger" })
    <hr />
    <input type="submit" value="Edit" class="btn btn-primary" />


</form>

University.Web/Views/Instructors/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<University.BL.DTOs.InstructorDTO>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<hr />
@Html.ActionLink("New Instructor", "Create", "Instructors", null, new { @class = "btn btn-sm btn-primary" })
<hr />
@using (Html.BeginForm("Index", "Instructors", FormMethod.Get))
{
    <p>
        <select name="PageSize" id="PageSize" class="form-control">
            <option @if ((int)ViewBag.PageSize == 5) { @Html.Raw("selected") }>
                5
            </option>
            <option @if ((int)ViewBag.PageSize == 10) { @Html.Raw("selected") }>
                10
            </option>
            <option @if ((int)ViewBag.PageSize == 15) { @Html.Raw("selected") }>
                15
            </option>

        </select>
        <br />
        <input type="submit" value="Apply" class="btn btn-primary" />
    </p>
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Last Name</th>
            <th>First MidName</th>
            <th>Hire Date</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ID</td>
                <td>@item.LastName</td>
                <td>@item.FirstMidName</td>
                <td>@item.HireDate</td>
                <td>
                    @Html.ActionLink("Departments", "Index", "Instructors", new { instructorID = item.ID }, new { @class = "btn btn-sm btn-info" })
                    @Html.ActionLink("Edit", "Edit", "Instructors", new { id = item.ID }, new { @class = "btn btn-sm btn-primary" })
                    @Html.ActionLink("Delete", "Delete", "Instructors", new { id = item.ID }, new { @class = "btn btn-sm btn-primary" })
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0: Model.PageNumber) of @Model.PageCount
<br />
Toatal Item Count @Model.TotalItemCount
@Html.PagedListPager(Model, page => Url.Action("Index", "Instructors", new { page, pageSize = ViewBag.PageSize }))

@if (ViewBag.Deparments != null)
{
<h1>Deparments</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>DeparmentID</th>
                <th>Name</th>
                <th>Budget</th>
                
            </tr>
        </thead>
        <tbody>
            @foreach (var item in (List<University.BL.DTOs.DepartmentDTO>)ViewBag.Deparments)
            {
                <tr>
                    <td>@item.DepartmentID</td>
                    <td>@item.Name</td>
                    <td>@item.Budget</td>
                    
                </tr>
            }
        </tbody>
    </table>
}