University.Web/Controllers/OfficeAssignmentsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using University.BL.Data;
using University.BL.DTOs;


namespace University.Web.Controllers
{
    public class OfficeAssignmentsController : Controller
    {

        private readonly UniversityContext context = new UniversityContext();
        // GET: OfficeAssignments
        public ActionResult Index()
        {
            //SELECT * FROM OfficeAssignments
            var query = context.OfficeAssignments.Include("Instructor").ToList();
            var offices = query.Select(x => new OfficeAssignmentDTO
            {
                InstructorID = x.InstructorID,
                Location = x.Location,
                Instructor = new InstructorDTO
                {
                    FirstMidName = x.Instructor.FirstMidName,
                    LastName = x.Instructor.LastName
                }


            });

            return View(offices);
        }


        [HttpGet]
        public ActionResult Create()
        {
            LoadData();

            return View();
        }
        [HttpPost]
        public ActionResult Create(OfficeAssignmentDTO office)
        {
            LoadData();


            if (!ModelState.IsValid)
            {
                return View(ModelState);
            }

            // INSERT INTO OfficeAssignments
            context.OfficeAssignments.Add(new BL.Models.OfficeAssignment
            {
                InstructorID = office.InstructorID,
                Location = office.Location
            });
            context.SaveChanges();

            return RedirectToAction("Index");


        }

        public void LoadData()
        {
            var Instructors = context.Instructors.Select(x => new InstructorDTO
            {

                ID = x.ID,
                FirstMidName = x.FirstMidName,
                LastName = x.LastName
            }).ToList();
            ViewData["Instructors"] = new SelectList(Instructors, "ID", "FullName");

        }

        [HttpGet]
        public ActionResult Edit(int instructorid)
        {

            var offices = context.OfficeAssignments.Where(x => x.InstructorID == instructorid)
                                          .Select(x => new OfficeAssignmentDTO
                                          {
                                              InstructorID = x.InstructorID,
                                              Location = x.Location
                                          }).FirstOrDefault();

            return View(offices);
        }

        [HttpPost]
        public ActionResult Edit(OfficeAssignmentDTO office)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(office);

                var officeModel = context.OfficeAssignments.FirstOrDefault(x => x.InstructorID == office.InstructorID);

                //campos que se van a modificar
                //sobreescribo las propiedades del modelo de base de datos
                officeModel.Location = office.Location;

                //aplique los cambios en base de datos
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View(office);
        }


        [HttpGet]
        public ActionResult Delete(int instructorid)
        {
            /*if (!context.OfficeAssignments.Any(x => x.InstructorID == instructorid))
            {*/
            //NO ES NECESARIO VALIDAR ELIMINA DIRECTO
            var officeModel = context.OfficeAssignments.FirstOrDefault(x => x.InstructorID == instructorid);
            context.OfficeAssignments.Remove(officeModel);
            context.SaveChanges();
            //}

            return RedirectToAction("Index");
        }

    }
}

University.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>University</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!-- Site -->
    <link rel="stylesheet" href="~/Content/Site.css">
    <script src="~/Scripts/Site.js"></script>
    <link rel="stylesheet" href="~/Content/PagedList.css" />
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- ============================================================== -->
        <!-- Sidebar -->
        <!-- ============================================================== -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">
                <img src="~/Assets/angular-icon.svg" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
                University
            </div>
            <div class="list-group list-group-flush">


                @Html.ActionLink("Students", "Index", "Students", null, new { @class = "list-group-item list-group-item-action list-group-item-success" })
                @Html.ActionLink("Instructors", "Index", "Instructors", null, new { @class = "list-group-item list-group-item-action list-group-item-primary" })
                @Html.ActionLink("Courses", "Index", "Courses", null, new { @class = "list-group-item list-group-item-action list-group-item-warning" })
                @Html.ActionLink("Offices", "Index", "OfficeAssignments", null, new { @class = "list-group-item list-group-item-action list-group-item-secondary" })
                @Html.ActionLink("Departments", "Index", "Departments", null, new { @class = "list-group-item list-group-item-action list-group-item-info" })


                @if (Request.IsAuthenticated)
                {

                }
                else
                {

                }
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page Content -->
        <!-- ============================================================== -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <i class="fas fa-align-justify" id="menu-toggle"></i>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    @Html.Partial("_LoginPartial")
                </div>
            </nav>
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Page Content -->
        <!-- ============================================================== -->
    </div>

    <!-- ============================================================== -->
    <!-- Menu Toggle Script -->
    <!-- ============================================================== -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>