University.Web/Controllers/DepartmentsController.cs
using PagedList;
using System;
using System.Linq;
using System.Web.Mvc;
using University.BL.Data;
using University.BL.DTOs;


namespace University.Web.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly UniversityContext context = new UniversityContext();

        // GET: Departments
        [HttpGet]
        public ActionResult Index(int? departmentid, int? pageSize, int? page)
        {
            #region Consluta Deparments
            var query = context.Departments.Include("Instructor").ToList();

            var deparments = query.Where(x => x.StartDate < DateTime.Now)
                .Select(x => new DepartmentDTO
                {
                    DepartmentID = x.DepartmentID,
                    Name = x.Name,
                    Budget = x.Budget,
                    StartDate = x.StartDate,
                    InstructorID = x.InstructorID,
                    Instructor = new InstructorDTO
                    {
                        FirstMidName = x.Instructor.FirstMidName,
                        LastName = x.Instructor.LastName
                    }
                }).ToList();
            #endregion
            #region Paginacion
            //Si viene nulo dele 10 por defecto
            pageSize = (pageSize ?? 10);
            //si viene igual por defecto llevelo a la 1 
            page = (page ?? 1);
            ViewBag.pageSize = pageSize;
            #endregion 
            return View(deparments.ToPagedList(page.Value, pageSize.Value));

        }

        [HttpGet]
        public ActionResult Create()
        {

            LoadData();
            return View();
        }

        [HttpPost]
        public ActionResult Create(DepartmentDTO department)
        {

            try
            {


                LoadData();

                if (!ModelState.IsValid)
                    return View(department);

                if (department.StartDate > DateTime.Now)
                    throw new Exception("La fecha no puede ser mayor a la fecha actual");
                context.Departments.Add(new BL.Models.Department
                {
                    Name = department.Name,
                    Budget = department.Budget,
                    StartDate = department.StartDate,
                    InstructorID = department.InstructorID

                });
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
            }


            return View(department);
        }
        public void LoadData()
        {
            var Instructors = context.Instructors.Select(x => new InstructorDTO
            {

                ID = x.ID,
                FirstMidName = x.FirstMidName,
                LastName = x.LastName
            }).ToList();
            ViewData["Instructors"] = new SelectList(Instructors, "ID", "FullName");

        }

        [HttpGet]
        public ActionResult Edit(int departmentid)
        {

            LoadData();
            var deparment = context.Departments.Where(x => x.DepartmentID == departmentid)
                                                .Select(x => new DepartmentDTO
                                                {
                                                    DepartmentID = x.DepartmentID,
                                                    Name = x.Name,
                                                    Budget = x.Budget,
                                                    StartDate = x.StartDate,
                                                    InstructorID = x.InstructorID

                                                }).FirstOrDefault();

            return View(deparment);
        }
        [HttpPost]
        public ActionResult Edit(DepartmentDTO department)
        {

            try
            {
                LoadData();

                if (!ModelState.IsValid)
                    return View(department);
                if (department.StartDate > DateTime.Now)
                    throw new Exception("La fecha no puede ser mayor a la fecha actual");
                var departmentModel = context.Departments.FirstOrDefault(x => x.DepartmentID == department.DepartmentID);

                departmentModel.Name = department.Name;
                departmentModel.Budget = department.Budget;
                departmentModel.StartDate = department.StartDate;
                departmentModel.InstructorID = department.InstructorID;
                //aplique cambios
                context.SaveChanges();
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);

            }
            return View(department);


        }

        [HttpGet]

        public ActionResult Delete(int departmentid)
        {
            var departmentModel = context.Departments.FirstOrDefault(x => x.DepartmentID == departmentid);
            context.Departments.Remove(departmentModel);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

    }//FIN PUBLIC CLASS CONTROLLER

} // FIN NAMESPACE

University.Web/Views/Departments/Create.cshtml
@model University.BL.DTOs.DepartmentDTO

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Department</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Budget, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Budget, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Budget, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InstructorID, "InstructorID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.InstructorID, (SelectList)ViewData["Instructors"], new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InstructorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <hr />
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

University.Web/Views/Departments/Edit.cshtml
@model University.BL.DTOs.DepartmentDTO

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Department</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DepartmentID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Budget, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Budget, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Budget, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InstructorID, "InstructorID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.InstructorID, (SelectList)ViewData["Instructors"], new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InstructorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <hr />
                <input type="submit" value="Edit" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

University.Web/Views/Departments/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<University.BL.DTOs.DepartmentDTO>
@{
    ViewBag.Title = "Index";
}

<h2>Welcome To Departments</h2>

<hr />
@Html.ActionLink("New Department", "Create", "Departments", null, new { @class = "btn btn-sm btn-outline-success" })
<hr />
@using (Html.BeginForm("Index", "Departments", FormMethod.Get))
{
    <p>
        <select name="PageSize" id="PageSize" class="form-control">
            <option @if ((int)ViewBag.PageSize == 5) { @Html.Raw("selected") }>
                5
            </option>
            <option @if ((int)ViewBag.PageSize == 10) { @Html.Raw("selected") }>
                10
            </option>
            <option @if ((int)ViewBag.PageSize == 15) { @Html.Raw("selected") }>
                15
            </option>

        </select>
        <br />
        <input type="submit" value="Apply" class="btn btn-outline-primary" />
    </p>
}

<table class="table table-bordered table-responsive table-responsive">
    <thead class="thead-dark">
        <tr>
            <th>DeparmentID</th>
            <th>Name</th>
            <th>Budget</th>
            <th>StartDate</th>
            <th>Instructor</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.DepartmentID</td>
                <td>@item.Name</td>
                <td>@item.Budget</td>
                <td>@item.StartDate</td>
                <td>@item.Instructor.FullName</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Departments", new { departmentid = item.DepartmentID }, new { @class = "btn btn-sm btn-info" })
                    @Html.ActionLink("Delete", "Delete", "Departments", new { departmentid = item.DepartmentID }, new { @class = "btn btn-sm btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0: Model.PageNumber) of @Model.PageCount
<br />
Total Item Count @Model.TotalItemCount
@Html.PagedListPager(Model, page => Url.Action("Index", "Departments", new { page, pageSize = ViewBag.PageSize }))